### ISSUE TITLE
Generate map from heightmap image

### ISSUE THREAD

**Issue by UnknownShadow200** [ClassiCube/MCGalaxy#184]

**Comment by Propolys** [comment]
Several issues I've encountered while trying to add this:
- Integrating the heightmap type in /newlvl and using the seed field as URL parameter will not be responsive as the map generators are unable to send any sort of feedback.
- Making a separate command for this could in fact work better BUT; it demands a large number of parameters (width, height, length, url - long, map name, noise strength), it doesn't work with existing maps or /os

Research brought up the following:
- Resizing the heightmap image to map sizes would work. Limiting the image maximum size is recommended since I suspect that big images will take a lot of time to resize, and lag the server as a consequence.
- Another possibility is to scale the coordinates of each block in 2D (top-view) and use the nearest-neighbor method. (I will likely try doing this to avoid System based operations)

**Comment by UnknownShadow200** [comment]
- You can still fetch the bitmap in the /newlvl code, since all commands are executed on a new separate thread.
- It would be best to keep as part of /newlvl, no need for a separate command.
- Perhaps the best method would be to have an extra command permission (similiar to say /zone) that defaults to superop, which allows generating a level from a heightmap.

**Comment by UnknownShadow200** [comment]
Done in 95284fab2e8f179930b923e062bb3f771f455630.
