### ISSUE TITLE
Bots search for players issues

### ISSUE THREAD

**Issue by YovelB** [ClassiCube/MCGalaxy#526]
A bot that searches for players during Hunt/Kill instructions quickly tries to finish the quest fast and goes to the next instruction without finishing the last one(actually getting to the player). I suggest you add a time limit for the bot to search any closest player and maybe it could be configurable.

**Comment by UnknownShadow200** [comment]
The `hunt` instruction doesn't finish until either:
a) There is no player within <search radius> 
b) It successfully hunt down a player

So it will always go onto the next instruction after successfully hunting down one player, but the player it is hunting can change since it recalculates the closest player every time the instruction is executed.
