### ISSUE TITLE
/checkpoint should place a client-side air_block after it's placed, similar to /mb air

### ISSUE THREAD

**Issue by xnotx123** [ClassiCube/MCGalaxy#552]
After placing a /checkpoint you have the /reload the map to get it to display properly, which is annoying. Also, if you delete the block (before reloading), it also actually _deletes_ the checkpoint, unlike something like /air_switch.

**Comment by Goodlyay** [comment]
This behavior is supposedly intentional with all blocks that appear as air (like op_air), I guess to show you where you placed them.
I agree that it's annoying though. It should echo back the block change and remove the one you placed.

In the mean time, I recommend simply standing where you want a checkpoint and doing /place checkpoint

**Comment by UnknownShadow200** [comment]
Although I'm not a fan of it, per discussion with Goodly I've implemented it in a separate branch with bb311668897b3204b926061953e4dad2c46f96a8. 
Once it's been tested to ensure it doesn't introduce new problems it will be merged into master.

**Comment by UnknownShadow200** [comment]
https://github.com/UnknownShadow200/MCGalaxy/pull/555
