### ISSUE TITLE
Survival test

### ISSUE THREAD

**Issue by Faris90** [ClassiCube/MCGalaxy#593]
Can you add survivaltest?

**Comment by UnknownShadow200** [comment]
Sorry but I'm not implementing survival mode.

**Comment by Faris90** [comment]
why not?

**Comment by UnknownShadow200** [comment]
Because it would take a lot of time and effort on my part.

And from past experience, what most people want from survival test/mode support is not just the actual original survival test mode - at the very least also want proper multiplayer support, but also generally tend to want features from modern Minecraft survival
