### ISSUE TITLE
Whitelist Doesn't Let You Join

### ISSUE THREAD

**Issue by sylv256** [ClassiCube/MCGalaxy#652]
# Screenshot
![image](https://user-images.githubusercontent.com/18603248/139958514-c5316517-ad20-4ec6-9582-37ba814bc91a.png)
# Logs
[2021-11-02.txt](https://github.com/UnknownShadow200/MCGalaxy/files/7464250/2021-11-02.txt)

**Comment by UnknownShadow200** [comment]
are you doing `/whitelist test` or `/whitelist test+`

**Comment by sylv256** [comment]
> are you doing `/whitelist test` or `/whitelist test+`

I did now. Why don't the docs say to use `[username]+`?

**Comment by UnknownShadow200** [comment]
Whether you need to use + at end of usernames is determined by the `classicube-account-plus` option in server.properties, which currently defaults to true/enabled

I agree that it's not that intuitive, and next version of MCGalaxy will change `classicube-account-plus` to default to false/disabled. 

(You may wish to change `classicube-account-plus` to `false` in server.properties so that you don't have to use + at end of usernames - note that this should only be changed for new servers)

**Comment by UnknownShadow200** [comment]
As of 59b79f038a6f2226225e57bfb1240bfa5cb6317e, `/whitelist` will also now automatically add `+` to end of names when `classicube-account-plus` mode is enabled
