### ISSUE TITLE
Expects standard input to not be empty

### ISSUE THREAD

**Issue by jedenastka** [ClassiCube/MCGalaxy#813]
Since 1.9.5.0, MCGalaxy expects standard input to not be empty, and exits with the message `** EOF, console no longer accepts input **` if it is. This breaks running the program as a service, because service managers (including systemd) provide managed services with an empty stdin, and is generally not expected from server software such as this.

I am not sure what was attempted by introducing this feature, but I might be able to suggest alternative solutions.

Currently, this can be worked around by providing fake input that never closes and never provides any data. A simple script to accomplish that can be found here: https://gitlab.com/-/snippets/3746794

**Reproducing**

On a *nix system, run the following command in the shell:

```sh
mono MCGalaxyCLI.exe < /dev/null
```

**Comment by UnknownShadow200** [comment]
The *EOF, console no longer accepts input* behaviour has always been there. After that message, MCGalaxy exits the console input loop and thus soon after the 'main' thread finishes.

This was an unintentional change caused by 07a1bd8925320d2c19796d67b0bcdc761ae54dc0

How .NET works is that as long as at least one non-background thread exists, the process will keep running.
This was not an issue previously because the main server threads were all non-background threads.

However, because that commit changed the main server threads to also be background threads, it meant that .NET now unexpectedly exits the process shortly after the EOF message because there are no non-background threads anymore.

**Comment by jedenastka** [comment]
I see, I have not noticed the message when testing against 1.9.4.9, but it clearly is here. Now the meaning of "console no longer accepts input" is clear - it just states that from now on you can't input commands. So this is just a bug.

> How .NET works is that as long as at least one non-background thread exists, the process will keep running.
> This was not an issue previously because the main server threads were all non-background threads.

This actually clears a lot of confusion I had about the code (I was attempting to make a merge request to fix this, but gave up). In languages I have experience with all threads are like background threads here, and you need to explicitly join them so the process doesn't exit.

**Comment by UnknownShadow200** [comment]
Given the severity of this issue I made another release.

**Comment by jedenastka** [comment]
Seems to be working.
